jobs:
  include:
    - stage: test
      name: Integration Tests
      if: branch = development
      services: docker
      script: npm run docker:test
    - stage: deploy
      name: Heroku Deployment
      language: node_js
      node_js: "10"
      script: npm run build
      deploy:
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app:
            development: lmnzr-dev-app
            master: lmnzr-staging-app
        - provider: heroku
          api_key: $HEROKU_API_KEY
          app: lmnzr-app
          on:
            tags: true
    - stage: ping-development
      if: branch = development
      script: "curl https://lmnzr-dev-app.herokuapp.com"
    - stage: ping-staging
      if: branch = master
      script: "curl https://lmnzr-staging-app.herokuapp.com"
    - stage: ping-production
      if: tag IS present
      script: "curl https://lmnzr-app.herokuapp.com"
