stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      services: docker
      script: npm run docker:test
    - stage: deploy
      language: node_js
      node_js: "10"
      script: npm run build      
    