jobs:
  include:
    - stage: Test & Build
      - name: Integration Tests
        services: docker
        script: npm run docker:test
      - name: Install Dependencies
        language: node_js
        node_js: "10"
        script: npm run build      
    