jobs:
  include:
    - stage: test
      if: branch = development
      services: docker
      script: npm run docker:test
    - stage: deploy
      language: node_js
      node_js: "10"
      script: npm run build
      deploy:
        provider: heroku
        api_key: $HEROKU_API_KEY
        app:
          development: lmnzr-dev-app
          master: lmnzr-dev-staging
