stages:
  - name: test
    services: docker
    script: npm run docker:test
  - name: deploy
    language: node_js
    node_js: "10"
    deploy:
      provider: heroku
      api_key: $HEROKU_API_KEY
      app: lmnzr-dev-app
